### ISSUE TITLE
Pets Despawn

### ISSUE THREAD

**Issue by Hedwig7s** [theseedmc/issues#37]
Pets like dogs and parrots despawn even with name tags

**Comment by yungwilder** [comment]
@Hedwig7s if the pet is in follow mode it is possible for it to travel with you and upon teleporting get stuck in the chunk you teleported from.as it becomes unloaded. If it is sitting then it may be due to mob cap in the area you are in. If it is not either of those things feel free to add more info, but as it stands the lack of info does not give the devs much to go on.

**Comment by gp-Airee** [comment]
Please use pets instead of the default Minecraft taming system.
